"""
config.py - константы корпуса в одном месте.

Раньше у меня список трейлеров был продублирован в parser.py и discover_repos.py:
стоило поправить один - второй молча расходился, и поиск кандидатов начинал
искать не то, что потом собирает parser. Теперь оба импортируют отсюда.
"""

import os
import shutil
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def rmtree_force(path: Path) -> None:
    """Удаление каталога вместе с git-объектами.

    Git создаёт файлы объектов только для чтения, и на Windows обычный shutil.rmtree
    падает на них с PermissionError (а с ignore_errors=True молча ничего не удаляет,
    после чего повторный запуск натыкается на «уже существует»)."""
    def _fix(func, p, *_):
        os.chmod(p, stat.S_IWRITE)
        func(p)
    if not Path(path).exists():
        return
    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=_fix)
    else:
        shutil.rmtree(path, onerror=_fix)


def setup_console() -> None:
    """UTF-8 для stdout/stderr. Если вывод перенаправлен (pipe, файл, IDE), Python на Windows
    кодирует его локалью (cp1251), и первый же символ вне неё (θ, ⚠, →) роняет скрипт
    посреди многочасового прогона. errors='replace' - на случай, если и UTF-8 не выйдет."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

# Метка инструмента -> фраза трейлера. Метка попадает в манифест, чтобы потом
# можно было смотреть Claude / Copilot / Cursor раздельно, а не одним куском.
# Поиск нечувствителен к регистру (git log -i): Claude Code пишет
# "Co-Authored-By" с заглавными, и регистрозависимый grep такие коммиты терял.
AI_TRAILER_MAP = {
    "claude": "Co-authored-by: Claude",
    "copilot": "Co-authored-by: Copilot",
    "cursor": "Co-authored-by: Cursor Agent",
}
AI_TRAILERS = list(AI_TRAILER_MAP.values())

# Граница human-корпуса. Всё, что раньше этой даты, гарантированно написано
# без AI-ассистентов с co-author трейлерами - так я обхожусь без ML-детектора,
# у которого была бы собственная (неизвестная мне) ошибка классификации.
HUMAN_CUTOFF = "2020-11-01"

# Расширение -> имя грамматики tree-sitter. Набор расширений совпадает с
# исходным RELEVANT_EXTS: определение корпуса молча не расширяю, это моё решение
# по исследованию, а не по инфраструктуре.
EXT_TO_LANG = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",  # грамматика javascript разбирает JSX сама
    ".ts": "typescript",
    ".tsx": "tsx",
    ".java": "java",
    ".c": "c",
    ".h": "c",  # заголовок C++ определяется отдельно, см. extract_comments
    ".cpp": "cpp",
    ".go": "go",
    ".rs": "rust",
}
RELEVANT_EXTS = set(EXT_TO_LANG)

# Читаемые имена для дашборда и отчётов.
LANG_LABELS = {
    "python": "Python", "javascript": "JavaScript", "typescript": "TypeScript",
    "tsx": "TSX", "java": "Java", "c": "C", "cpp": "C++", "go": "Go", "rust": "Rust",
}

# Пути, чьи комментарии писал не автор коммита: вендоренный или сгенерированный
# код. Такие файлы в корпусе - шум, причём разный по объёму в AI и human выборках.
SKIP_PATH_PATTERNS = [
    r"(^|/)node_modules/",
    r"(^|/)vendor(s)?/",
    r"(^|/)third[_-]?party/",
    r"(^|/)dist/",
    r"(^|/)build/",
    r"(^|/)\.venv/",
    r"(^|/)site-packages/",
    r"\.min\.(js|css)$",
    r"\.bundle\.js$",
    r"_pb2(_grpc)?\.py$",
    r"\.pb\.go$",
    r"(^|/)package-lock\.json$",
    r"\.generated\.",
    r"(^|/)generated/",
]

# Значения по умолчанию для parser.py (их же показывает --help).
DEFAULT_MAX_FILE_KB = 512
DEFAULT_MAX_FILES_PER_COMMIT = 200
DEFAULT_MAX_FILES_PER_REPO = 2000
DEFAULT_SEED = 42

# Фразы, по которым parser.py ищет "подозрительные" коммиты: похожи на
# сгенерированные, но известного трейлера нет. Этот список сообщает, что
# AI_TRAILERS неполон (см. раздел Limitations).
SUSPECT_PATTERNS = [
    "Generated with Claude Code",
    "Generated with [Claude Code]",
    "Generated by Copilot",
    "aider:",
    "Generated-by:",
    "Generated by Cursor",
]

# Порог overlap, с которого комментарий считается пересказом кода.
# Значение по умолчанию, не истина: итоговый вывод строится на кривой
# чувствительности (counter.py), а порог калибруется ручной разметкой (validate.py).
DEFAULT_THETA = 0.5
# Комментарии короче этого числа содержательных слов не оцениваю:
# на одном-двух словах доля пересечения принимает только значения 0, 0.5, 1.
MIN_CONTENT_WORDS = 3

SCHEMA_VERSION = 1
